const CONFIG = {
  MATERY_HOME_BANNER_ENABLE: true,
  MATERY_HOME_BANNER_GREETINGS: [
    'Xây Dựng Quang Long',
    'Nhận xây nhà trọn gói',
    'Hỗ trợ trả góp 0% lãi suất',
    'Khảo sát miễn phí tận nơi'
  ],

  MATERY_HOME_NAV_BUTTONS: true,
  MATERY_HOME_NAV_BACKGROUND_IMG_FIXED: false,
  MATERY_SHOW_START_READING: true,

  MATERY_MENU_CATEGORY: true,
  MATERY_MENU_TAG: true,
  MATERY_MENU_ARCHIVE: true,
  MATERY_MENU_SEARCH: true,

  MATERY_POST_LIST_COVER: true,
  MATERY_POST_LIST_SUMMARY: true,
  MATERY_POST_LIST_PREVIEW: true,

  MATERY_ARTICLE_ADJACENT: true,
  MATERY_ARTICLE_COPYRIGHT: true,
  MATERY_ARTICLE_NOT_BY_AI: false,
  MATERY_ARTICLE_RECOMMEND: true,

  MATERY_WIDGET_LATEST_POSTS: true,
  MATERY_WIDGET_ANALYTICS: false,
  MATERY_WIDGET_TO_TOP: true,
  MATERY_WIDGET_TO_COMMENT: true,
  WIDGET_DARK_MODE: true,
  MATERY_WIDGET_TOC: true
}
export default CONFIG
